name: Build Electron (Windows)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-win:
    runs-on: windows-latest
    permissions:
      contents: write  # required for creating GitHub Releases
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app (Windows)
        run: npm run build:electron -- -p never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: twitch-tts-reader-win
          path: |
            dist/*.exe
            dist/*.yml

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.exe
            dist/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
